CREATE TABLE NEWS(
	 NNUM		VARCHAR2(20)	PRIMARY KEY
	,NNAME		VARCHAR2(300)
	,NTITLE		VARCHAR2(300)
	,NCONTENT	VARCHAR2(300)
	,NPHOTO		VARCHAR2(300)
	,DELETEYN	VARCHAR2(1)
	,INSERTDATE		DATE
	,UPDATEDATE		DATE
);
DROP TABLE NEWS;